### ISSUE TITLE
year scaling

### ISSUE THREAD

**Issue by Lewis-Barnett-NOAA** [stephbrodie1/WRAP_Location_CaseStudy#4]
Just noticed that in the GLMMs, the year variable was not scaled (mean centered and divided by SD) externally.  At one point, we were doing this internally in sdmTMB, but not sure it was applied in this case (would depend on the version of sdmTMB this was last run on, does anyone have a record of that?).  Probably good to note the release that the code was run on.

Thanks for bearing with the software in its early stages.  Much of the syntax has changed in the latest version.  @ericward-noaa or I can help update if needed.

**Comment by stephbrodie1** [comment]
Version added to manuscript supplementary material.
